# Develop override settings

url: http://localhost:4000

analytics:
  provider: "google-universal"
  google:
    tracking_id          : "UA-181535155-1"

comments:
  disqus:
    shortname            : "m053m716"

sass:
  style: expanded